Appraiser/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from estimation.views import *
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="ibk/templatemo_497_upper/templatemo_497_upper/index.html")),
    url(r'^admin/', admin.site.urls),
    url(r'^estimation/',include('estimation.urls', namespace='estimation')),
    url(r'^ibk/', include('ibk.urls', namespace='ibk'))
]

ibk/urls.py
from django.conf.urls import url
from ibk.views import *
from . import views

urlpatterns = [
    #$를 붙이면 해당 주소 뒤로 다른 url이 추가되어도 각각 다 처리할 수 있고 $이 없다면 특정 주소 뒤로 어떠한 url이 오더라도 해당 url에서 지정한 view에서 모두 처리한다
    url(r'^$', upload_file, name='upload'),
    # ?p<parameter 이름>파라미터 값 형태로 url을 통해 파라미터를 넘길 수 있다
    url(r'^page/(?P<code>R(\d+)-(\d+))/', show_normal_report, name='page'),
    url(r'download/$', download, name='download'),
]

ibk/models.py
from django.db import models

# Create your models here.
class Document(models.Model):
    file = models.FileField(upload_to='documents')
    title = models.CharField(max_length=100, null=False)

    def __str__(self):
        return self.title

ibk/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render,redirect
from django.views.generic import *
#  파일을 import 할 때 from 에서 .을 이용하면 파일경로를 전부 칠 필요없이 현재 파일이 속한 파일의 다른 파일들을 가져올 수 있다
from .forms import UploadFileForm, ExcelForm
from .models import Document
from django.core.urlresolvers import reverse_lazy
from django.template import RequestContext
from .function import *
import xlrd
from django import shortcuts
from django.core.files import File
import os
import urllib.request
import xmltodict

#get으로 해당 페이지에 접속하면 파일을 업로드할 수 있는 폼을 제공, 파일을 업로드해서 업로드버튼을 누르면 해당 파일에 있는 데이터로 각 사건에 대해 보기를 제공
def upload_file(request):
    if request.method == 'POST':
        form=UploadFileForm(request.POST, request.FILES)

        #자신이 만든 폼의 필드는 기본값으로 required=true 로 되어 있으므로 모든 필드가 입력되지 않으면 유효하지 않다
        if form.is_valid():
            new_document=Document(file=request.FILES['file'])
            new_document.title=new_document.file.name
            workbook =excel_handling().make_file(new_document.file)
            normal_datas=excel_handling().get_normal(workbook)
            normal_codes=excel_handling().get_normal_code(workbook)
            normal_zip=zip(normal_datas, normal_codes)
            file=Document.objects.filter(title=new_document.title)
            animal = ['cat', 'dog', 'mause']
            how_many = ['one', 'two', 'three']
            data = zip(animal, how_many)

            #해당파일이 이미 존재하면 저장하지 않고 해당파일이 없다면 해당 파일의 데이터 모델을 저장한다
            if(len(file)==0):
                new_document.save()

            return render(request,'ibk/templatemo_497_upper/templatemo_497_upper/code_selection.html', {'normals':normal_zip, 'file':new_document, 'codes':data})

    else:
        form=UploadFileForm()

    return render(request,'ibk/templatemo_497_upper/templatemo_497_upper/form.html',{'form':form})

#탁감 보고서를 작성하기 위해 엑셀데이터에서 필요한 데이터를 추출해서 html 페이지로 데이터를 보내준다
def show_normal_report(request, code):
    name=request.GET['title']
    file=Document.objects.get(title=name)
    loc=0;
    workbook = excel_handling().make_file(file.file)
    #모든 데이터로 데이터 집합을 구해 보통 같은 행의 데이터는 하나의 대상에 대한 곧통의 데이터를 가르키므로 해당 행의 위치를 구해 나머지도 구한다
    codes = excel_handling().get_all_code(workbook)
    while(loc<len(codes)):
        if(codes[loc]==code):
            break
        else:
            loc=loc+1
    borrow_name=excel_handling().get_render_name(workbook, loc)    #Borrow Name
    program_title=excel_handling().get_program_title(workbook)  #Program
    property_control_no=excel_handling().get_property_control_no(workbook,loc) #Property Control No
    court=excel_handling().get_court(workbook,loc)  #관할법원
    case=excel_handling().get_case_number(workbook, loc)    #사건번호
    borrower_num=excel_handling().get_render_index(workbook, loc)   #차주일련번호
    opb=excel_handling().get_opb(workbook, borrower_num)    #OPB
    interest=excel_handling().get_accured_interest(workbook, borrower_num)  #연체이자
    setup_price=excel_handling().get_cpma(workbook, loc) #설정액
    address=excel_handling().get_address(workbook, loc, code)    #Address
    category=excel_handling().get_property_category(workbook, loc)  #Property category
    label=['가','나','다','라','마','바','사','아','자','차','카','타','파','하']
    ho=excel_handling().get_ho(workbook, code)  #건물의 호들
    liensize_improvement=excel_handling().get_liensize_improvement(workbook, code)  #전유면적 - 일단 엑셀에서 건물면적을 꺼내서 구함
    liensize_improvement_py=[]
    for index in liensize_improvement:
        index=round(float(index)/3.3,2)
        liensize_improvement_py.append(index)

    landsize=excel_handling().get_landsize(workbook, code)  #대지권 면적
    landsize_py=[]
    for index in landsize:
        index=round(float(index)/3.3,2)
        landsize_py.append(index)
    sum_ho=len(ho)
    sum_liensize_improvement=0
    sum_liensize_improvement_py= 0
    sum_landsize=0
    sum_landsize_py= 0
    for a in liensize_improvement:
        sum_liensize_improvement=sum_liensize_improvement+round(float(a),2)
    for a in liensize_improvement_py:
        sum_liensize_improvement_py=sum_liensize_improvement_py+round(float(a),2)
    for a in landsize:
        sum_landsize=sum_landsize+round(float(a),2)
    for a in landsize_py:
        sum_landsize_py=sum_landsize_py+round(float(a),2)
    sum_liensize_improvement=round(sum_liensize_improvement,2)
    sum_liensize_improvement_py=round(sum_liensize_improvement_py,2)
    sum_landsize=round(sum_landsize,2)
    sum_landsize_py=round(sum_landsize_py,2)


    building = zip(label, ho, liensize_improvement, liensize_improvement_py, landsize, landsize_py)
    utensil = excel_handling().get_utensil(workbook, loc)  # 기계기구의 숫자
    address_code=excel_handling().get_address_code(workbook,loc)

    #url = 'http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcSHRent?LAWD_CD=11110&DEAL_YMD=201702&serviceKey=KqP4dQTZbN2QbXZlZUK0gYsfRfqiACwnmgqPf3N2yPqj%2F7Ura0eDpY1CKVPmzzQRqGS3myGv3Oauhw7YmfPDLg%3D%3D'
    #data = urllib.request.urlopen(url).read()
    #sample=xmltodict.parse(data)['response']['body']['items']['item'][1]['계약면적']

    #download_url=excel_write().save_file(program_title, opb, property_control_no, interest, setup_price)

    return render(request, 'ibk/report.html',
                  {'code':code,'borrow_name':borrow_name, 'program':program_title, 'property_control_no':property_control_no, 'court':court, 'case':case, 'opb':opb,
                   'interest':interest, 'setup_price':setup_price, 'address':address, 'category':category, 'building':building, 'utensil':utensil,
                   'address_code':address_code, 'sum_ho':sum_ho, 'sum_liensize_improvement':sum_liensize_improvement,
                   'sum_liensize_improvement_py':sum_liensize_improvement_py, 'sum_landsize':sum_landsize, 'sum_landsize_py':sum_landsize_py})

def download(request):
    if request.method == 'POST':
        form = ExcelForm(request.POST)
        #form은 valid 검사를 하고 나서야 cleaned_data를 가진다
        if form.is_valid():
            #dictionary 형태로 선언하기 위해서는 중괄호 {} 로 선언해야 한다
            user_input={}
            #결과요약
            user_input['program'] = form.cleaned_data['program']
            user_input['opb'] = form.cleaned_data['opb']
            user_input['interest'] = form.cleaned_data['interest']
            user_input['property_control_no'] = form.cleaned_data['property_control_no']
            user_input['setup_price'] = form.cleaned_data['setup_price']
            user_input['user'] = form.cleaned_data['user']
            user_input['user_phone'] = form.cleaned_data['user_phone']  # 담당자 연락처
            user_input['credit_amount'] = form.cleaned_data['credit_amount'] # 총 채권액
            user_input['borrow_name'] = form.cleaned_data['borrow_name']  # borrow name
            user_input['law_price'] = form.cleaned_data['law_price']  # 법사가
            user_input['market_predict'] = form.cleaned_data['market_predict']  # 시장전망
            user_input['market_price'] = form.cleaned_data['market_price']  # 시장가
            user_input['law_price_comp1'] = form.cleaned_data['law_price_comp1']  # 법사가 대비 1
            user_input['market_price_comp1'] = form.cleaned_data['market_price_comp1']    # 시장가 대비 1
            user_input['opb_comp1'] = form.cleaned_data['opb_comp1']  # opb 대비 1
            user_input['court'] = form.cleaned_data['court']  # 관할법원
            user_input['bid'] = form.cleaned_data['bid']  # 낙찰가
            user_input['law_price_comp2'] = form.cleaned_data['law_price_comp2']  # 법사가 대비 2
            user_input['market_price_comp2'] = form.cleaned_data['market_price_comp2']  # 시장가 대비 2
            user_input['opb_comp2'] = form.cleaned_data['opb_comp2']  # opb 대비 2
            user_input['case'] = form.cleaned_data['case']  # 사건번호
            user_input['avg_bid'] = form.cleaned_data['avg_bid']  # 평균낙찰가
            user_input['law_price_comp3'] = form.cleaned_data['law_price_comp3']  # 법사가 대비 3
            user_input['market_price_comp3'] = form.cleaned_data['market_price_comp3']  # 시장가 대비 3
            user_input['opb_comp3'] = form.cleaned_data['opb_comp3']  # opb 대비 3
            user_input['submission_date'] = form.cleaned_data['submission_date']  # 법원제출일
            user_input['next_date'] = form.cleaned_data['next_date']  # 차기기일
            user_input['fail_count'] = form.cleaned_data['fail_count']  # 유찰회수

            #본건현황
            user_input['address'] = form.cleaned_data['address']  # Address
            user_input['property_category'] = form.cleaned_data['property_category']  # Property category
            user_input['usage'] = form.cleaned_data['usage']  # 용도지역
            user_input['land_category'] = form.cleaned_data['land_category']  # 지목
            user_input['state'] = form.cleaned_data['state']  # 이용상황
            user_input['land_price_m'] = form.cleaned_data['land_price_m']  # 개별공시지가 m
            user_input['land_price_py'] = form.cleaned_data['land_price_py']  # 개별공시지가 py
            user_input['land_size_m'] = form.cleaned_data['land_size_m']  # 전체토지면적 m
            user_input['land_size_py'] = form.cleaned_data['land_size_py']  # 전체토지면적 py
            user_input['security_size_m'] = form.cleaned_data['security_size_m']  # 담보면적 m
            user_input['security_size_py'] = form.cleaned_data['security_size_py']  # 담보면적 py
            user_input['structure'] = form.cleaned_data['structure']  # 건물 구조
            user_input['permission_date'] = form.cleaned_data['permission_date']  # 사용승인일
            user_input['floor_usage'] = form.cleaned_data['floor_usage']  # 층별 용도
            user_input['exclusive_rate'] = form.cleaned_data['exclusive_rate']  # 전용율
            user_input['exclusive_area_m'] = form.cleaned_data['exclusive_area_m']  # 전유면적 m
            user_input['exclusive_area_py'] = form.cleaned_data['exclusive_area_py']  # 전유면적 py
            user_input['contract_area_m'] = form.cleaned_data['contract_area_m']  # 계약면적 m

ibk/templates/ibk/templatemo_497_upper/templatemo_497_upper/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Atools</title>
<!--
Upper Template
http://www.templatemo.com/tm-497-upper
-->
    {% load staticfiles %}
    <!-- load stylesheets -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400">
    <!-- Google web font "Open Sans" -->
    <link rel="stylesheet" href="{% static "font-awesome-4.5.0/css/font-awesome.min.css" %}">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
    <!-- Bootstrap style -->
    <link rel="stylesheet" href="{% static "css/hero-slider-style.css" %}">
    <!-- Hero slider style (https://codyhouse.co/gem/hero-slider/) -->
    <link rel="stylesheet" href="{% static "css/magnific-popup.css" %}">
    <!-- Magnific popup style (http://dimsemenov.com/plugins/magnific-popup/) -->
    <link rel="stylesheet" href="{% static "css/templatemo-style.css" %}">
    <!-- Templatemo style -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
          <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
          <![endif]-->
</head>

    <body>

        <!-- Content -->
        <div class="cd-hero">

            <!-- Navigation -->
            <div class="cd-slider-nav">
                <nav class="navbar">
                    <div class="tm-navbar-bg">

                        <a class="navbar-brand text-uppercase " href="/"><i class="fa fa-flash tm-brand-icon"></i>Atools</a>

                        <button class="navbar-toggler hidden-lg-up" type="button" data-toggle="collapse" data-target="#tmNavbar">
                            &#9776;
                        </button>
                        <div class="collapse navbar-toggleable-md text-xs-center text-uppercase tm-navbar" id="tmNavbar">
                            <ul class="nav navbar-nav">
                                <li class="nav-item active selected">
                                    <a class="nav-link" href="#" data-no="1">File Upload<span class="sr-only">(current)</span></a>
                                </li>

                            </ul>
                        </div>
                    </div>

                </nav>
            </div>

            <ul class="cd-hero-slider">



                <!-- Page 2 Gallery One -->
                <li class="selected">
                    <div class="cd-full-width">
                        <div class="container-fluid js-tm-page-content" data-page-no="2" data-page-type="gallery">
                            <div class="tm-img-gallery-container">
                                <div class="tm-img-gallery">
                                <!-- Gallery One pop up connected with JS code below -->
                                    <div class="tm-img-gallery-info-container">
                                        <h1 class="tm-text-title tm-gallery-title tm-white"><span class="tm-white">IBK기업은행</span></h1>
                                        <p class="tm-text"></p>
                                    </div>

                                <div class="panel-body">
                                   <form action="{% url 'ibk:upload' %}" method="post" enctype="multipart/form-data">
                                       {% csrf_token %}
                                       <p >{{ form.non_field_errors }}</p>
                                       <p style="background-color: transparent; color: #ddffdd; font-weight: bold; font-size: 22px ">{{ form.file.label }}</p>
                                       <p style="background-color: transparent; color: #FFFFFF; font-weight: bold; font-size: 15px ">
                                           {{ form.file.errors }}
                                           {{ form.file }}
                                       </p>
                                       <input type="submit" value="Upload">
                                   </form>
                                </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </li>

            </ul> <!-- .cd-hero-slider -->

            <footer class="tm-footer">

            </footer>

        </div> <!-- .cd-hero -->


        <!-- Preloader, https://ihatetomatoes.net/create-custom-preloading-screen/ -->
        <div id="loader-wrapper">

            <div id="loader"></div>
            <div class="loader-section section-left"></div>
            <div class="loader-section section-right"></div>

        </div>

        {% load staticfiles %}
        <!-- load JS files -->
        <script src="{% static "js/jquery-1.11.3.min.js" %}"></script>         <!-- jQuery (https://jquery.com/download/) -->
        <script src="https://www.atlasestateagents.co.uk/javascript/tether.min.js"></script> <!-- Tether for Bootstrap (http://stackoverflow.com/questions/34567939/how-to-fix-the-error-error-bootstrap-tooltips-require-tether-http-github-h) -->
        <script src="{% static "js/bootstrap.min.js" %}"></script>             <!-- Bootstrap js (v4-alpha.getbootstrap.com/) -->
        <script src="{% static "js/hero-slider-main.js" %}"></script>          <!-- Hero slider (https://codyhouse.co/gem/hero-slider/) -->
        <script src="{% static "js/jquery.magnific-popup.min.js" %}"></script> <!-- Magnific popup (http://dimsemenov.com/plugins/magnific-popup/) -->

        <script>

            function adjustHeightOfPage(pageNo) {

                var offset = 80;
                var pageContentHeight = 0;

                var pageType = $('div[data-page-no="' + pageNo + '"]').data("page-type");

                if( pageType != undefined && pageType == "gallery") {
                    pageContentHeight = $(".cd-hero-slider li:nth-of-type(" + pageNo + ") .tm-img-gallery-container").height();
                }
                else {
                    pageContentHeight = $(".cd-hero-slider li:nth-of-type(" + pageNo + ") .js-tm-page-content").height();
                }

                if($(window).width() >= 992) { offset = 120; }
                else if($(window).width() < 480) { offset = 40; }

                // Get the page height
                var totalPageHeight = 15 + $('.cd-slider-nav').height()
                                        + pageContentHeight + offset
                                        + $('.tm-footer').height();

                // Adjust layout based on page height and window height
                if(totalPageHeight > $(window).height())
                {
                    $('.cd-hero-slider').addClass('small-screen');
                    $('.cd-hero-slider li:nth-of-type(' + pageNo + ')').css("min-height", totalPageHeight + "px");
                }
                else
                {
                    $('.cd-hero-slider').removeClass('small-screen');
                    $('.cd-hero-slider li:nth-of-type(' + pageNo + ')').css("min-height", "100%");
                }
            }

            /*
                Everything is loaded including images.
            */
            $(window).load(function(){

                adjustHeightOfPage(1); // Adjust page height

                /* Gallery One pop up
                -----------------------------------------*/
                $('.gallery-two').magnificPopup({
                    delegate: 'a', // child items selector, by clicking on it popup will open
                    type: 'image',
                    gallery:{enabled:true}
                });

				/* Gallery Two pop up
                -----------------------------------------*/
				/*
				$('.gallery-two').magnificPopup({
                    delegate: 'a',
                    type: 'image',
                    gallery:{enabled:true}
                });*/

                /* Gallery Three pop up
                -----------------------------------------*/


                /* Collapse menu after click
                -----------------------------------------*/
                $('#tmNavbar a').click(function(){
                    $('#tmNavbar').collapse('hide');

                    adjustHeightOfPage($(this).data("no")); // Adjust page height
                });

                /* Browser resized
                -----------------------------------------*/
                $( window ).resize(function() {
                    var currentPageNo = $(".cd-hero-slider li.selected .js-tm-page-content").data("page-no");

                    // wait 3 seconds
                    setTimeout(function() {
                        adjustHeightOfPage( currentPageNo );
                    }, 1000);

                });

                // Remove preloader (https://ihatetomatoes.net/create-custom-preloading-screen/)
                $('body').addClass('loaded');

            });

            /* Google map
            ------------------------------------------------*/
            var map = '';
            var center;

            function initialize() {
                var mapOptions = {
                    zoom: 15,
                    center: new google.maps.LatLng(37.769725, -122.462154),
                    scrollwheel: false
                };

                map = new google.maps.Map(document.getElementById('google-map'),  mapOptions);

                google.maps.event.addDomListener(map, 'idle', function() {
                  calculateCenter();
                });

                google.maps.event.addDomListener(window, 'resize', function() {
                  map.setCenter(center);
                });
            }

            function calculateCenter() {
                center = map.getCenter();
            }

            function loadGoogleMap(){
                var script = document.createElement('script');
                script.type = 'text/javascript';
                script.src = 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&' + 'callback=initialize';
                document.body.appendChild(script);
            }

            // DOM is ready
            $(function() {
                loadGoogleMap(); // Google Map
            });

        </script>

</body>
</html>